require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const User = require('../models/User');
const Group = require('../models/Group');
const GroupMember = require('../models/GroupMember');
const Transaction = require('../models/Transaction');
const FundRequest = require('../models/FundRequest');
const ActivityLog = require('../models/ActivityLog');
const Notification = require('../models/Notification');

async function seed() {
  await mongoose.connect(process.env.MONGO_URI, { serverSelectionTimeoutMS: 30000 });
  console.log('✅ Connected to MongoDB');

  const db = mongoose.connection.db;
  const cols = await db.listCollections().toArray();
  for (const col of cols) await db.dropCollection(col.name);
  console.log('🗑️  All collections dropped');

  // Users
  const pw = await bcrypt.hash('demo1234', 12);
  const [santosh, priya, ravi] = await User.insertMany([
    { name: 'Santosh Kumar', email: 'admin@demo.com', username: 'santosh', password: pw },
    { name: 'Priya Sharma', email: 'member@demo.com', username: 'priya', password: pw },
    { name: 'Ravi Verma', email: 'ravi@demo.com', username: 'ravi', password: pw },
  ]);
  console.log('👤 Users created');

  // Groups (groupCode auto-generated by pre-save hook)
  const group1 = await Group.create({ name: 'Office Supplies Fund', description: 'Monthly fund for office stationery and supplies', createdBy: santosh._id, currentBalance: 12500 });
  const group2 = await Group.create({ name: 'Team Outing 2025', description: 'Annual team outing planning fund', createdBy: priya._id, currentBalance: 8500 });
  console.log(`📁 Groups created — Codes: ${group1.groupCode}, ${group2.groupCode}`);

  // Memberships
  await GroupMember.insertMany([
    { group: group1._id, user: santosh._id, role: 'admin', status: 'active', joinedAt: new Date(Date.now() - 7 * 86400000) },
    { group: group1._id, user: priya._id, role: 'member', status: 'active', joinedAt: new Date(Date.now() - 5 * 86400000) },
    { group: group1._id, user: ravi._id, role: 'member', status: 'active', joinedAt: new Date(Date.now() - 3 * 86400000) },
    { group: group2._id, user: priya._id, role: 'admin', status: 'active', joinedAt: new Date(Date.now() - 6 * 86400000) },
    { group: group2._id, user: santosh._id, role: 'member', status: 'active', joinedAt: new Date(Date.now() - 4 * 86400000) },
    { group: group2._id, user: ravi._id, role: 'member', status: 'pending' },
  ]);
  console.log('👥 Memberships created');

  // Transactions
  await Transaction.create({ group: group1._id, type: 'fund-added', amount: 15000, addedBy: santosh._id, remarks: 'Initial project funding', createdAt: new Date(Date.now() - 7 * 86400000) });
  await Transaction.create({ group: group1._id, type: 'transfer-completed', amount: 2500, addedBy: priya._id, remarks: 'Printer cartridges', createdAt: new Date(Date.now() - 2 * 86400000) });
  await Transaction.create({ group: group2._id, type: 'fund-added', amount: 8500, addedBy: priya._id, remarks: 'Team contributions collected', createdAt: new Date(Date.now() - 6 * 86400000) });
  console.log('💰 Transactions created');

  // Fund Request (pending)
  const req1 = await FundRequest.create({
    group: group1._id, requestedBy: priya._id,
    amount: 3500, purpose: 'Office chair repair',
    description: 'The ergonomic chair in cabin 3 needs a new base and gas cylinder replacement.',
    status: 'pending',
  });

  // Completed request
  const req2 = await FundRequest.create({
    group: group1._id, requestedBy: ravi._id,
    amount: 2500, purpose: 'Printer cartridges',
    description: 'Need to replace black + colour ink cartridges for HP LaserJet.',
    status: 'completed', approvedBy: santosh._id, approvedAt: new Date(Date.now() - 3 * 86400000),
    transferredBy: santosh._id, transferredAt: new Date(Date.now() - 2 * 86400000),
    receivedAt: new Date(Date.now() - 2 * 86400000), completedAt: new Date(Date.now() - 2 * 86400000),
  });
  console.log('📋 Fund requests created');

  // Activity Logs
  await ActivityLog.insertMany([
    { group: group1._id, user: santosh._id, action: 'Santosh Kumar added ₹15,000 to the group', createdAt: new Date(Date.now() - 7 * 86400000) },
    { group: group1._id, user: ravi._id, action: 'Ravi Verma requested ₹2,500 for "Printer cartridges"', createdAt: new Date(Date.now() - 3 * 86400000) },
    { group: group1._id, user: santosh._id, action: "Santosh Kumar approved Ravi Verma's request for ₹2,500", createdAt: new Date(Date.now() - 3 * 86400000 + 300000) },
    { group: group1._id, user: santosh._id, action: 'Santosh Kumar marked ₹2,500 as transferred to Ravi Verma', createdAt: new Date(Date.now() - 2 * 86400000) },
    { group: group1._id, user: ravi._id, action: 'Ravi Verma confirmed receipt of ₹2,500 — balance updated to ₹12,500', createdAt: new Date(Date.now() - 2 * 86400000 + 300000) },
    { group: group1._id, user: priya._id, action: 'Priya Sharma requested ₹3,500 for "Office chair repair"', createdAt: new Date(Date.now() - 86400000) },
    { group: group2._id, user: priya._id, action: 'Priya Sharma added ₹8,500 to the group', createdAt: new Date(Date.now() - 6 * 86400000) },
  ]);
  console.log('📜 Activity logs created');

  // Notifications
  await Notification.insertMany([
    { recipient: santosh._id, type: 'request_raised', title: 'New Fund Request', message: 'Priya Sharma requested ₹3,500 for "Office chair repair"', relatedGroup: group1._id, relatedRequest: req1._id },
    { recipient: ravi._id, type: 'join_request', title: 'Group Invite', message: 'Priya Sharma invited you to join "Team Outing 2025"', relatedGroup: group2._id },
    { recipient: ravi._id, type: 'request_approved', title: 'Request Approved', message: 'Your request for ₹2,500 was approved by Santosh Kumar', relatedGroup: group1._id, relatedRequest: req2._id, read: true },
  ]);
  console.log('🔔 Notifications created');

  console.log('\n✅ V2 Database seeded successfully!\n');
  console.log('Demo Accounts (password: demo1234):');
  console.log(`  📧 admin@demo.com   → Santosh (Admin of "${group1.name}" [${group1.groupCode}])`);
  console.log(`  📧 member@demo.com  → Priya   (Member of "${group1.name}", Admin of "${group2.name}" [${group2.groupCode}])`);
  console.log(`  📧 ravi@demo.com    → Ravi    (Member of "${group1.name}", Pending invite to "${group2.name}")`);
  console.log('');

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => { console.error('❌ Seed failed:', err.message); process.exit(1); });
